
version: '3.8'

services:
  currency-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: spi-currency-app
    ports:
      - "8080:8080"
    environment:
      - CURRENCY_API_KEY=din_api_nyckel
      # Lägg till andra miljövariabler här
    tty: true
    stdin_open: true
